version: '2.23.3'
services:
  node-app:
  
    image: issashergy/node-app-docker
    build: .

    # environment:
    #   - PORT=7070
    #   - NODE_ENV=production
    depends_on:
      -  postgres
    deploy:
      replicas: 4  
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    env_file:
      - ./.env
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
 
  redis:
    image: redis
  nginx:
   image: nginx
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   ports:
   - "1010:80"
   depends_on:
    - node-app
 
volumes:
 
  postgres-db:
  